CREATE TABLE IF NOT EXISTS AUDITTRAIL (
	ID INTEGER IDENTITY(1,1) NOT NULL,
	ENTITYTYPE VARCHAR2(100) NOT NULL,
	ENTITYID CHAR(50) NOT NULL,
	IPADDRESS CHAR(10) NULL,
	CHANGES CLOB NULL,
	TITLE VARCHAR2(200) NULL,
	DESCRIPTION VARCHAR2(500) NULL,
	STATUS INTEGER NULL,
	CREATEBY VARCHAR2(50) NULL,
	CREATEBYNAME VARCHAR2(100) NULL,
	CREATEDATE TIMESTAMP(6) NULL,
	LASTUPDATEBY VARCHAR2(50) NULL,
	LASTUPDATEBYNAME VARCHAR2(100) NULL,
	LASTUPDATEDATE TIMESTAMP(6) NULL,
	CONSTRAINT PK_AUDITTRAIL PRIMARY KEY (ID)
);