CREATE TABLE "AUDITTRAIL"
(
 "ID" INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 "ENTITYTYPE" NVARCHAR(100 char) NOT NULL,
 "ENTITYID" NCHAR(50 char) NOT NULL,
 "IPADDRESS" NCHAR(10 char) NULL,
 "CHANGES" TEXT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);