DROP TABLE IF EXISTS `AuditTrail`;
CREATE TABLE `AuditTrail` (
	`ID` INT AUTO_INCREMENT  NOT NULL,
	`EntityType` VARCHAR(100) CHARACTER SET utf8mb4  NOT NULL,
	`EntityID` VARCHAR(100) CHARACTER SET utf8mb4  NOT NULL,
	`IPAddress` VARCHAR(20) CHARACTER SET utf8mb4  NULL,
	`Changes` LONGTEXT CHARACTER SET utf8mb4  NULL,
	`Title` VARCHAR(200) CHARACTER SET utf8mb4  NULL,
	`Description` VARCHAR(500) CHARACTER SET utf8mb4  NULL,
	`Status` INT  NULL,
	`CreateBy` VARCHAR(50) CHARACTER SET utf8mb4  NULL,
	`CreatebyName` VARCHAR(100) CHARACTER SET utf8mb4  NULL,
	`CreateDate` DATETIME  NULL,
	`LastUpdateBy` VARCHAR(50) CHARACTER SET utf8mb4  NULL,
	`LastUpdateByName` VARCHAR(100) CHARACTER SET utf8mb4  NULL,
	`LastUpdateDate` DATETIME  NULL,
	PRIMARY KEY (`ID`)
);