CREATE TABLE "VIDEODETAILWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "CUSTOMERCLASS" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_VIDEODETAILWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "VIDEOGALLERY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "RAWDATA" TEXT NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "VIDEOLISTWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "VIDEOTYPEID" INT NULL,
 "DETAILPAGEURL" NVARCHAR(255 char) NULL,
 "ISPAGEABLE" BIT NOT NULL,
 "PAGESIZE" INT NULL,
   CONSTRAINT "PK_VIDEOLISTWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "VIDEOTOPWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "VIDEOTYPEID" INT NULL,
 "TOPS" INT NULL,
 "SUBTITLE" NVARCHAR(255 char) NULL,
 "MORELINK" NVARCHAR(255 char) NULL,
 "DETAILPAGEURL" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_VIDEOTOPWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "VIDEOTYPE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "NAME" NVARCHAR(100 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "PARENTID" INT NULL,
 "STATUS" INT NULL,
 "SEOTITLE" NVARCHAR(100 char) NULL,
 "SEOKEYWORD" NVARCHAR(100 char) NULL,
 "SEODESCRIPTION" NVARCHAR(300 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "CONTENTID" NVARCHAR(100 char) NULL,
 "CULTUREID" INT NULL,
 "DISPLAYORDER" INT NULL,
   CONSTRAINT "PK_VIDEOTYPE"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "VIDEOTYPEWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "VIDEOTYPEID" INT NULL,
 "TARGETPAGE" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_VIDEOTYPEWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "VIDEOWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "WIDTH" INT NULL,
 "HEIGHT" INT NULL,
 "URL" NVARCHAR(255 char) NULL,
 "CODE" NVARCHAR(500 char) NULL,
   CONSTRAINT "PK_VIDEOWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "APPLICATIONSETTING"
(
 "SETTINGKEY" NVARCHAR(50 char) NOT NULL,
 "VALUE" TEXT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "ARTICLE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "SUMMARY" NVARCHAR(255 char) NULL,
 "METAKEYWORDS" NVARCHAR(255 char) NULL,
 "METADESCRIPTION" NVARCHAR(255 char) NULL,
 "COUNTER" INT NULL,
 "ARTICLETYPEID" INT NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "ARTICLECONTENT" TEXT NULL,
 "STATUS" INT NULL,
 "IMAGETHUMBURL" NVARCHAR(255 char) NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "ISPUBLISH" BIT NOT NULL,
 "PUBLISHDATE" TIMESTAMP(7) NULL,
 "URL" NVARCHAR(100 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "ARTICLEDETAILWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "CUSTOMERCLASS" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_ARTICLEDETAILWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ARTICLEGALLERY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "RAWDATA" TEXT NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "ARTICLELISTWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "ARTICLETYPEID" INT NULL,
 "DETAILPAGEURL" NVARCHAR(255 char) NULL,
 "ISPAGEABLE" BIT NOT NULL,
 "PAGESIZE" INT NULL,
   CONSTRAINT "PK_ARTICLELISTWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ARTICLESUMMARYWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SUBTITLE" NVARCHAR(255 char) NULL,
 "STYLE" NVARCHAR(255 char) NULL,
 "DETAILLINK" NVARCHAR(255 char) NULL,
 "SUMMARY" TEXT NULL
);
CREATE TABLE "ARTICLETOPWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "ARTICLETYPEID" INT NULL,
 "TOPS" INT NULL,
 "SUBTITLE" NVARCHAR(255 char) NULL,
 "MORELINK" NVARCHAR(255 char) NULL,
 "DETAILPAGEURL" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_ARTICLETOPWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ARTICLETYPE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "PARENTID" INT NULL,
 "URL" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "SEOTITLE" NVARCHAR(100 char) NULL,
 "SEOKEYWORD" NVARCHAR(100 char) NULL,
 "SEODESCRIPTION" NVARCHAR(300 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DISPLAYORDER" INT NULL,
   CONSTRAINT "PK_ARTICLETYPE"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ARTICLETYPEWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "ARTICLETYPEID" INT NULL,
 "TARGETPAGE" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_ARTICLETYPEWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "BASKET"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERID" NVARCHAR(50 char) NOT NULL,
 "IMAGEURL" NVARCHAR(500 char) NOT NULL,
 "QUANTITY" INT NOT NULL,
 "PRICE" DECIMAL(18,4) NOT NULL,
 "PRODUCTID" INT NOT NULL,
 "PROMOCODE" NVARCHAR(50 char) NULL,
 "TITLE" NVARCHAR(200 char) NOT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_BASKET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CAROUSEL"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "HEIGHT" INT NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_CAROUSEL"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CAROUSELITEM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "CAROUSELID" INT NULL,
 "CAROUSELWIDGETID" NVARCHAR(100 char) NULL,
 "TARGETLINK" NVARCHAR(255 char) NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_CAROUSELITEM"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CAROUSELWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "CAROUSELID" INT NULL,
   CONSTRAINT "PK_CAROUSELWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CMS_LAYOUT"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "LAYOUTNAME" NVARCHAR(255 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "CONTAINERCLASS" NVARCHAR(255 char) NULL,
 "STATUS" INT NULL,
 "DESCRIPTION" TEXT NULL,
 "SCRIPT" NVARCHAR(255 char) NULL,
 "STYLE" NVARCHAR(255 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "IMAGETHUMBURL" NVARCHAR(255 char) NULL,
 "THEME" NVARCHAR(255 char) NULL
);
CREATE TABLE "CMS_LAYOUTHTML"
(
 "LAYOUTHTMLID" INT IDENTITY(1,1) NOT NULL,
 "LAYOUTID" NVARCHAR(100 char) NOT NULL,
 "PAGEID" NVARCHAR(100 char) NULL,
 "HTML" TEXT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "CMS_MEDIA"
(
 "ID" NVARCHAR(50 char) NOT NULL,
 "PARENTID" NVARCHAR(50 char) NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "MEDIATYPE" INT NULL,
 "URL" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
   CONSTRAINT "PK_CMS_MEDIA"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CMS_MESSAGE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "EMAIL" NVARCHAR(50 char) NOT NULL,
 "POSTMESSAGE" TEXT NOT NULL,
 "REPLY" TEXT NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DESCRIPTION" NVARCHAR(200 char) NULL
);
CREATE TABLE "CMS_PAGE"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "REFERENCEPAGEID" NVARCHAR(100 char) NULL,
 "ISPUBLISHEDPAGE" BIT NULL,
 "PARENTID" NVARCHAR(100 char) NULL,
 "PAGENAME" NVARCHAR(100 char) NULL,
 "ISHOMEPAGE" BIT NOT NULL,
 "URL" NVARCHAR(255 char) NULL,
 "LAYOUTID" NVARCHAR(100 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "CONTENT" TEXT NULL,
 "DISPLAYORDER" INT NULL,
 "DESCRIPTION" TEXT NULL,
 "STATUS" INT NULL,
 "ISPUBLISH" BIT NOT NULL,
 "PUBLISHDATE" TIMESTAMP(7) NULL,
 "METAKEYWORLDS" NVARCHAR(255 char) NULL,
 "METADESCRIPTION" NVARCHAR(255 char) NULL,
 "SCRIPT" NVARCHAR(255 char) NULL,
 "STYLE" NVARCHAR(255 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "CMS_REDIRECTION"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(200 char) NOT NULL,
 "INCOMINGURL" NVARCHAR(500 char) NOT NULL,
 "DESTINATIONURL" NVARCHAR(500 char) NOT NULL,
 "ISPERMANENT" BIT NOT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "ISPATTERN" BIT NULL,
   CONSTRAINT "PK_CMS_REDIRECTION"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CMS_RULE"
(
 "RULEID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "ZONENAME" NVARCHAR(50 char) NULL,
 "RULEEXPRESSION" NVARCHAR(800 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "RULEITEMS" TEXT NULL
);
CREATE TABLE "CMS_THEME"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "URL" NVARCHAR(100 char) NULL,
 "URLDEBUGGER" NVARCHAR(100 char) NULL,
 "THUMBNAIL" NVARCHAR(100 char) NULL,
 "ISACTIVED" BIT NULL,
 "STATUS" INT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_CMS_THEME"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "CMS_WIDGETBASE"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "WIDGETNAME" NVARCHAR(255 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "POSITION" INT NULL,
 "LAYOUTID" NVARCHAR(100 char) NULL,
 "PAGEID" NVARCHAR(100 char) NULL,
 "ZONEID" NVARCHAR(100 char) NULL,
 "PARTIALVIEW" NVARCHAR(255 char) NULL,
 "ASSEMBLYNAME" NVARCHAR(255 char) NULL,
 "SERVICETYPENAME" NVARCHAR(255 char) NULL,
 "VIEWMODELTYPENAME" NVARCHAR(255 char) NULL,
 "FORMVIEW" NVARCHAR(255 char) NULL,
 "STYLECLASS" NVARCHAR(1000 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DESCRIPTION" TEXT NULL,
 "STATUS" INT NULL,
 "ISTEMPLATE" BIT DEFAULT 0
 NULL,
 "THUMBNAIL" NVARCHAR(200 char) NULL,
 "ISSYSTEM" BIT DEFAULT 0
 NULL,
 "EXTENDDATA" TEXT NULL,
 "RULEID" INT NULL
);
CREATE TABLE "CMS_ZONE"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "LAYOUTID" NVARCHAR(100 char) NULL,
 "PAGEID" NVARCHAR(100 char) NULL,
 "ZONENAME" NVARCHAR(255 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DESCRIPTION" TEXT NULL,
 "STATUS" INT NULL,
 "HEADINGCODE" NVARCHAR(100 char) NULL
);
CREATE TABLE "COMMENTS"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "PAGEPATH" NVARCHAR(300 char) NULL,
 "USERID" NVARCHAR(100 char) NULL,
 "PICTURE" NVARCHAR(300 char) NULL,
 "USERNAME" NVARCHAR(100 char) NULL,
 "COMMENTCONTENT" NVARCHAR(500 char) NULL,
 "AGREES" INT NULL,
 "DISAGREES" INT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_COMMENTS"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
ALTER TABLE "VIDEOGALLERY" ADD CONSTRAINT "PK__VIDEOGAL__3214EC278E8E9CA6" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "APPLICATIONSETTING" ADD CONSTRAINT "PK_APPLICATIONSETTING" NOT CLUSTER  PRIMARY KEY("SETTINGKEY") ;
ALTER TABLE "ARTICLE" ADD CONSTRAINT "PK_ARTICLE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "ARTICLEGALLERY" ADD CONSTRAINT "PK__ARTICLEG__3214EC2726D53115" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "ARTICLESUMMARYWIDGET" ADD CONSTRAINT "PK_ARTICLESUMMARYWIDGET" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "CMS_LAYOUT" ADD CONSTRAINT "PK_CMS_LAYOUT" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "CMS_LAYOUTHTML" ADD CONSTRAINT "PK_CMS_LAYOUTHTML" NOT CLUSTER  PRIMARY KEY("LAYOUTHTMLID") ;
ALTER TABLE "CMS_MESSAGE" ADD CONSTRAINT "PK_CMS_MESSAGE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "CMS_PAGE" ADD CONSTRAINT "PK_CMS_PAGE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "CMS_RULE" ADD CONSTRAINT "PK_CMS_RULE" NOT CLUSTER  PRIMARY KEY("RULEID") ;
ALTER TABLE "CMS_WIDGETBASE" ADD CONSTRAINT "PK_CMS_WIDGETBASE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "CMS_ZONE" ADD CONSTRAINT "PK_CMS_ZONE" NOT CLUSTER  PRIMARY KEY("ID") ;
CREATE TABLE "CURRENCY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "CODE" NVARCHAR(10 char) NULL,
 "SYMBOL" NVARCHAR(10 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK__CURRENCY__3214EC277F38B9CD"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "DATAARCHIVED"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "DATA" TEXT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "DATADICTIONARY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "DICNAME" NVARCHAR(255 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DICVALUE" NVARCHAR(255 char) NULL,
 "ORDER" INT NULL,
 "PID" INT NULL,
 "ISSYSTEM" BIT NOT NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "IMAGETHUMBURL" NVARCHAR(255 char) NULL,
 "DESCRIPTION" TEXT NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "DBVERSION"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MAJOR" INT NULL,
 "MINOR" INT NULL,
 "REVISION" INT NULL,
 "BUILD" INT NULL,
   CONSTRAINT "PK__DBVERSIO__3214EC27E67228EE"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "EA_ACTIONBODY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "BODY" TEXT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "EA_EVENTACTION"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "EVENT" NVARCHAR(100 char) NULL,
 "ACTIONS" TEXT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "EA_PENDINGTASK"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "IDENTIFIER" NVARCHAR(200 char) NOT NULL,
 "HANDLERNAME" NVARCHAR(100 char) NOT NULL,
 "DATA" TEXT NULL,
 "LOGMESSAGE" TEXT NULL,
 "RETRYCOUNT" INT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "EXTENDFIELD"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "VALUE" TEXT NULL,
 "OWNERMODULE" NVARCHAR(50 char) NULL,
 "OWNERID" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL
);
CREATE TABLE "FLUIDCONTENTGROUP"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "ICON" NVARCHAR(100 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK__FLUIDCON__3214EC2716EA0FB5"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "FLUIDCONTENTTEMPLATE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(100 char) NULL,
 "APPLYTO" NVARCHAR(100 char) NULL,
 "TEMPLATE" TEXT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "FLUIDCONTENTTYPE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(100 char) NULL,
 "CONTENTSCHEMA" TEXT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "GROUPID" INT NULL,
 "ROLEID" INT NULL,
 "ICON" NVARCHAR(100 char) NULL
);
CREATE TABLE "FLUIDCONTENTVALUE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "CONTENTTYPEID" INT NULL,
 "TITLE" NVARCHAR(100 char) NULL,
 "CONTENT" TEXT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "CONTENTID" NVARCHAR(100 char) NULL,
 "CULTUREID" INT NULL,
 "URL" NVARCHAR(200 char) NULL,
 "SEOTITLE" NVARCHAR(200 char) NULL,
 "SEOKEYWORD" NVARCHAR(200 char) NULL,
 "SEODESCRIPTION" NVARCHAR(200 char) NULL
);
CREATE TABLE "FORMDATA"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(500 char) NULL,
 "FORMID" VARCHAR(50) NOT NULL,
 "STATUS" INT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_FORMDATA_1"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "FORMDATAITEM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "FORMDATAID" INT NOT NULL,
 "FIELDID" VARCHAR(50) NULL,
 "FIELDTEXT" NVARCHAR(1000 char) NULL,
 "FIELDVALUE" TEXT NULL,
 "OPTIONVALUE" VARCHAR(50) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "FORMS"
(
 "ID" VARCHAR(50) NOT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "FIELDSDATA" TEXT NULL,
 "NOTIFICATIONRECEIVER" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "HTMLWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "HTML" TEXT NULL
);
CREATE TABLE "IMAGEWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "WIDTH" INT NULL,
 "HEIGHT" INT NULL,
 "ALTTEXT" NVARCHAR(255 char) NULL,
 "LINK" NVARCHAR(255 char) NULL,
 "IMAGEURLMD" NVARCHAR(225 char) NULL,
 "IMAGEURLSM" NVARCHAR(225 char) NULL,
   CONSTRAINT "PK_IMAGEWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "NAVIGATION"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "PARENTID" NVARCHAR(100 char) NULL,
 "URL" NVARCHAR(255 char) NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "ISMOBILE" BIT NULL,
 "HTML" TEXT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "DISPLAYORDER" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "NAVIGATIONWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "CUSTOMERCLASS" NVARCHAR(255 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "LOGO" NVARCHAR(255 char) NULL,
 "ALIGNCLASS" NVARCHAR(50 char) NULL,
 "ISTOPFIX" BIT NULL,
 "ROOTID" NVARCHAR(100 char) NULL,
 "SHOWBASKET" BIT NULL,
   CONSTRAINT "PK_NAVIGATIONWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ORDER"
(
 "ID" NVARCHAR(50 char) NOT NULL,
 "USERID" NVARCHAR(50 char) NOT NULL,
 "CONTACT" NVARCHAR(50 char) NULL,
 "PHONENUMBER" NVARCHAR(50 char) NULL,
 "TOTAL" DECIMAL(18,4) NOT NULL,
 "ORDERSTATUS" INT NOT NULL,
 "PAYTIME" TIMESTAMP(7) NULL,
 "COMPLETEPAYTIME" TIMESTAMP(7) NULL,
 "TRACKINGNUMBER" NVARCHAR(50 char) NULL,
 "LOGISTICSCOMPANY" NVARCHAR(50 char) NULL,
 "SHIPPINGADDRESS" NVARCHAR(500 char) NULL,
 "PAYMENTGATEWAY" NVARCHAR(50 char) NULL,
 "PAYMENTID" NVARCHAR(500 char) NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "REFUNDID" NVARCHAR(100 char) NULL,
 "REFUND" DECIMAL(18,4) NULL,
 "REFUNDDATE" TIMESTAMP(7) NULL,
 "REFUNDREASON" NVARCHAR(500 char) NULL,
 "SHIPPINGOPTION" INT NULL,
 "SUBTOTAL" DECIMAL(19,4) NULL,
 "TAX" DECIMAL(19,4) NULL,
 "SHIPPING" DECIMAL(19,4) NULL,
   CONSTRAINT "PK_ORDER"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ORDERITEM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "ORDERID" NVARCHAR(50 char) NOT NULL,
 "USERID" NVARCHAR(50 char) NOT NULL,
 "IMAGEURL" NVARCHAR(500 char) NOT NULL,
 "QUANTITY" INT NOT NULL,
 "PRICE" DECIMAL(18,4) NOT NULL,
 "PRODUCTID" INT NOT NULL,
 "PROMOCODE" NVARCHAR(50 char) NULL,
 "TITLE" NVARCHAR(200 char) NOT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "BASKETID" INT NULL,
   CONSTRAINT "PK_ORDERITEM"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PAGEVIEW"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "PAGEURL" NVARCHAR(500 char) NULL,
 "PAGETITLE" NVARCHAR(200 char) NULL,
 "IPADDRESS" NVARCHAR(50 char) NULL,
 "SESSIONID" NVARCHAR(50 char) NULL,
 "USERAGENT" NVARCHAR(500 char) NULL,
 "REFERER" NVARCHAR(1000 char) NULL,
 "REFERERNAME" NVARCHAR(255 char) NULL,
 "KEYWORDS" NVARCHAR(255 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_PAGEVIEW"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PERMISSION"
(
 "PERMISSIONKEY" NVARCHAR(100 char) NOT NULL,
 "ROLEID" INT NOT NULL,
 "TITLE" NVARCHAR(100 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "MODULE" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK__PERMISSION_PERMISSIONKEY_ROLEID"  CLUSTER PRIMARY KEY("PERMISSIONKEY","ROLEID") ENABLE 
);
CREATE TABLE "PERSISTKEY"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "XML" TEXT NULL,
 "CREATIONDATE" TIMESTAMP(7) NULL,
 "ACTIVATIONDATE" TIMESTAMP(7) NULL,
 "EXPIRATIONDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "PRODUCT"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "IMAGETHUMBURL" NVARCHAR(255 char) NULL,
 "BRANDCD" INT NULL,
 "PRODUCTCATEGORYID" INT NULL,
 "COLOR" NVARCHAR(255 char) NULL,
 "PRICE" DECIMAL(19,4) NULL,
 "REBATEPRICE" DECIMAL(19,4) NULL,
 "PURCHASEPRICE" DECIMAL(19,4) NULL,
 "NORM" NVARCHAR(255 char) NULL,
 "SHELFLIFE" NVARCHAR(255 char) NULL,
 "PRODUCTCONTENT" TEXT NULL,
 "DESCRIPTION" TEXT NULL,
 "ISPUBLISH" BIT NOT NULL,
 "PUBLISHDATE" TIMESTAMP(7) NULL,
 "STATUS" INT NULL,
 "SEOTITLE" NVARCHAR(255 char) NULL,
 "SEOKEYWORD" NVARCHAR(255 char) NULL,
 "SEODESCRIPTION" TEXT NULL,
 "ORDERINDEX" INT NULL,
 "SOURCEFROM" NVARCHAR(255 char) NULL,
 "URL" NVARCHAR(255 char) NULL,
 "TARGETFROM" NVARCHAR(255 char) NULL,
 "TARGETURL" NVARCHAR(255 char) NULL,
 "PARTNUMBER" NVARCHAR(200 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "PRODUCTCATEGORY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "PARENTID" INT NULL,
 "URL" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "SEOTITLE" NVARCHAR(100 char) NULL,
 "SEOKEYWORD" NVARCHAR(100 char) NULL,
 "SEODESCRIPTION" NVARCHAR(300 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "DISPLAYORDER" INT NULL,
   CONSTRAINT "PK_PRODUCTCATEGORY"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PRODUCTCATEGORYTAG"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "PRODUCTCATEGORYID" INT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "PARENTID" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_PRODUCTCATEGORYTAG"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PRODUCTCATEGORYWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "PRODUCTCATEGORYID" INT NULL,
 "TARGETPAGE" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_PRODUCTCATEGORYWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PRODUCTDETAILWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "CUSTOMERCLASS" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_PRODUCTDETAILWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PRODUCTGALLERY"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "RAWDATA" TEXT NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "PRODUCTIMAGE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "PRODUCTID" INT NULL,
 "IMAGEURL" NVARCHAR(500 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_PRODUCTIMAGE"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PRODUCTLISTWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "ISPAGEABLE" BIT NOT NULL,
 "PRODUCTCATEGORYID" INT NULL,
 "DETAILPAGEURL" NVARCHAR(255 char) NULL,
 "COLUMNS" NVARCHAR(255 char) NULL,
 "PAGESIZE" INT NULL,
   CONSTRAINT "PK_PRODUCTLISTWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "PRODUCTTAG"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "PRODUCTID" INT NULL,
 "TAGID" INT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
   CONSTRAINT "PK_PRODUCTTAG"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "ROLES"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(100 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK__ROLES__3214EC2709F27024"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SCRIPTWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SCRIPT" TEXT NULL
);
CREATE TABLE "SECTIONCONTENT"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "SECTIONGROUPID" NVARCHAR(100 char) NOT NULL,
 "SECTIONCONTENTTYPE" INT NULL,
 "ORDER" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_SECTIONCONTENT"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SECTIONCONTENTCALLTOACTION"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "INNERTEXT" NVARCHAR(255 char) NULL,
 "HREF" NVARCHAR(255 char) NULL,
   CONSTRAINT "PK_SECTIONCONTENTCALLTOACTION"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SECTIONCONTENTIMAGE"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "IMAGESRC" NVARCHAR(255 char) NULL,
 "IMAGEALT" NVARCHAR(255 char) NULL,
 "IMAGETITLE" NVARCHAR(255 char) NULL,
 "HREF" NVARCHAR(255 char) NULL,
 "WIDTH" INT NULL,
 "HEIGHT" INT NULL,
   CONSTRAINT "PK_SECTIONCONTENTIMAGE"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SECTIONCONTENTPARAGRAPH"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "HTMLCONTENT" TEXT NULL
);
CREATE TABLE "SECTIONCONTENTTITLE"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "INNERTEXT" NVARCHAR(255 char) NULL,
 "HREF" NVARCHAR(255 char) NULL,
 "TITLELEVEL" NVARCHAR(10 char) NULL,
   CONSTRAINT "PK_SECTIONCONTENTTITLE"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SECTIONCONTENTVIDEO"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "VIDEOTITLE" NVARCHAR(200 char) NULL,
 "THUMBNAIL" NVARCHAR(200 char) NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "WIDTH" INT NULL,
 "HEIGHT" INT NULL,
 "URL" NVARCHAR(256 char) NULL,
 "CODE" TEXT NULL
);
CREATE TABLE "SECTIONGROUP"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "GROUPNAME" NVARCHAR(255 char) NULL,
 "SECTIONWIDGETID" NVARCHAR(100 char) NOT NULL,
 "PARTIALVIEW" NVARCHAR(100 char) NULL,
 "ORDER" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "PERCENTWIDTH" NVARCHAR(100 char) NULL,
   CONSTRAINT "PK_SECTIONGROUP"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SECTIONTEMPLATE"
(
 "TEMPLATENAME" NVARCHAR(100 char) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "THUMBNAIL" NVARCHAR(100 char) NULL,
 "EXAMPLEDATA" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_SECTIONTEMPLATE"  CLUSTER PRIMARY KEY("TEMPLATENAME") ENABLE 
);
CREATE TABLE "SECTIONWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "SECTIONTITLE" NVARCHAR(255 char) NULL,
 "ISHORIZONTAL" BIT NULL,
   CONSTRAINT "PK_SECTIONWIDGET"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "SHIPPINGOPTION"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "PRICE" DECIMAL(19,4) NULL,
 "RULE" TEXT NULL,
 "CONTENTID" NVARCHAR(100 char) NULL,
 "CULTUREID" INT NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL
);
CREATE TABLE "STYLESHEETWIDGET"
(
 "ID" NVARCHAR(100 char) NOT NULL,
 "STYLESHEET" TEXT NULL
);
CREATE TABLE "SUBSCRIPTION"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "EMAIL" NVARCHAR(100 char) NULL,
 "PHONE" NVARCHAR(100 char) NULL,
 "REFERRER" NVARCHAR(500 char) NULL,
 "ISVALIDATE" BIT NULL,
 "TITLE" NVARCHAR(200 char) NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "STATUS" INT NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK__SUBSCRIP__3214EC278DE8304A"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "USERROLERELATION"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "ROLEID" INT NULL,
 "USERID" NVARCHAR(50 char) NULL,
   CONSTRAINT "PK__USERROLE__3214EC27F3C9AC02"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
CREATE TABLE "USERS"
(
 "USERID" NVARCHAR(50 char) NOT NULL,
 "PASSWORD" NVARCHAR(255 char) NULL,
 "APILOGINTOKEN" NVARCHAR(255 char) NULL,
 "LASTLOGINDATE" TIMESTAMP(7) NULL,
 "LOGINIP" NVARCHAR(50 char) NULL,
 "PHOTOURL" NVARCHAR(255 char) NULL,
 "TIMESTAMP" BIGINT NULL,
 "USERNAME" NVARCHAR(100 char) NULL,
 "USERTYPECD" INT NULL,
 "ADDRESS" NVARCHAR(255 char) NULL,
 "AGE" INT NULL,
 "BIRTHDAY" TIMESTAMP(7) NULL,
 "BIRTHPLACE" NVARCHAR(255 char) NULL,
 "EMAIL" NVARCHAR(100 char) NULL,
 "ENGLISHNAME" NVARCHAR(50 char) NULL,
 "FIRSTNAME" NVARCHAR(50 char) NULL,
 "HOBBY" NVARCHAR(100 char) NULL,
 "LASTNAME" NVARCHAR(50 char) NULL,
 "MARITALSTATUS" INT NULL,
 "MOBILEPHONE" NVARCHAR(50 char) NULL,
 "NICKNAME" NVARCHAR(50 char) NULL,
 "PROFESSION" NVARCHAR(50 char) NULL,
 "QQ" NVARCHAR(50 char) NULL,
 "SCHOOL" NVARCHAR(50 char) NULL,
 "SEX" INT NULL,
 "TELEPHONE" NVARCHAR(50 char) NULL,
 "ZIPCODE" NVARCHAR(50 char) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "STATUS" INT NULL,
 "DESCRIPTION" NVARCHAR(500 char) NULL,
 "RESETTOKEN" NVARCHAR(50 char) NULL,
 "RESETTOKENDATE" TIMESTAMP(7) NULL,
   CONSTRAINT "PK_USERS"  CLUSTER PRIMARY KEY("USERID") ENABLE 
);
CREATE TABLE "VIDEO"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "NAME" NVARCHAR(100 char) NULL,
 "TITLE" NVARCHAR(255 char) NULL,
 "SUMMARY" NVARCHAR(255 char) NULL,
 "METAKEYWORDS" NVARCHAR(255 char) NULL,
 "METADESCRIPTION" NVARCHAR(255 char) NULL,
 "COUNTER" INT NULL,
 "VIDEOTYPEID" INT NULL,
 "DESCRIPTION" NVARCHAR(255 char) NULL,
 "VIDEOURL" NVARCHAR(255 char) NULL,
 "VIDEOCODE" NVARCHAR(1000 char) NULL,
 "DURATION" NVARCHAR(100 char) NULL,
 "STATUS" INT NULL,
 "IMAGETHUMBURL" NVARCHAR(255 char) NULL,
 "IMAGEURL" NVARCHAR(255 char) NULL,
 "ISPUBLISH" BIT NOT NULL,
 "PUBLISHDATE" TIMESTAMP(7) NULL,
 "CREATEBY" NVARCHAR(50 char) NULL,
 "CREATEBYNAME" NVARCHAR(100 char) NULL,
 "CREATEDATE" TIMESTAMP(7) NULL,
 "LASTUPDATEBY" NVARCHAR(50 char) NULL,
 "LASTUPDATEBYNAME" NVARCHAR(100 char) NULL,
 "LASTUPDATEDATE" TIMESTAMP(7) NULL,
 "CONTENTID" NVARCHAR(100 char) NULL,
 "CULTUREID" INT NULL,
   CONSTRAINT "PK_VIDEO"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
ALTER TABLE "DATAARCHIVED" ADD CONSTRAINT "PK_DATAARCHIVED" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "DATADICTIONARY" ADD CONSTRAINT "PK_DATADICTIONARY" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "EA_ACTIONBODY" ADD CONSTRAINT "PK_ACTIONBODY" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "EA_EVENTACTION" ADD CONSTRAINT "PK_EVENTACTION" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "EA_PENDINGTASK" ADD CONSTRAINT "PK_EA_PENDINGTASK" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "EXTENDFIELD" ADD CONSTRAINT "PK_EXTENDFIELD" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "FLUIDCONTENTTEMPLATE" ADD CONSTRAINT "PK_FLUIDCONTENTTEMPLATE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "FLUIDCONTENTTYPE" ADD CONSTRAINT "PK_FLUIDCONTENTTYPE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "FLUIDCONTENTVALUE" ADD CONSTRAINT "PK_FLUIDCONTENTVALUE" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "FORMDATAITEM" ADD CONSTRAINT "PK_FORMDATA" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "FORMS" ADD CONSTRAINT "PK_FORMS" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "HTMLWIDGET" ADD CONSTRAINT "PK_HTMLWIDGET" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "NAVIGATION" ADD CONSTRAINT "PK_NAVIGATION" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "PERSISTKEY" ADD CONSTRAINT "PK__PERSISTK__3214EC279EE7DAA6" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "PRODUCTGALLERY" ADD CONSTRAINT "PK__PRODUCTG__3214EC27D2116C5B" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SCRIPTWIDGET" ADD CONSTRAINT "PK_SCRIPTWIDGET" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SECTIONCONTENTPARAGRAPH" ADD CONSTRAINT "PK_SECTIONCONTENTPARAGRAPH" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SECTIONCONTENTVIDEO" ADD CONSTRAINT "PK_SECTIONCONTENTVIDEO" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SHIPPINGOPTION" ADD CONSTRAINT "PK__SHIPPING__3214EC27634ED9E6" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "STYLESHEETWIDGET" ADD CONSTRAINT "PK_STYLESHEETWIDGET" NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "HTMLWIDGET" ADD CONSTRAINT "FK_HTMLWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "IMAGEWIDGET" ADD CONSTRAINT "FK_IMAGEWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "NAVIGATIONWIDGET" ADD CONSTRAINT "FK_NAVIGATIONWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "PERMISSION" ADD CONSTRAINT "FK_PERMISSION_PERMISSION_ROLE" FOREIGN KEY("ROLEID") REFERENCES "ZKEACMS"."ROLES"("ID") ;
ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_PRODUCTCATEGORY" FOREIGN KEY("PRODUCTCATEGORYID") REFERENCES "ZKEACMS"."PRODUCTCATEGORY"("ID") ;
ALTER TABLE "PRODUCTCATEGORYWIDGET" ADD CONSTRAINT "FK_PRODUCTCATEGORYWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "PRODUCTDETAILWIDGET" ADD CONSTRAINT "FK_PRODUCTDETAILWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "PRODUCTLISTWIDGET" ADD CONSTRAINT "FK_PRODUCTLISTWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "SCRIPTWIDGET" ADD CONSTRAINT "FK_SCRIPTWIDGET_CMS_WIDGETBASE" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "SECTIONCONTENT" ADD CONSTRAINT "FK_SECTIONCONTENT_WIDGET" FOREIGN KEY("SECTIONWIDGETID") REFERENCES "ZKEACMS"."SECTIONWIDGET"("ID") ;
ALTER TABLE "SECTIONGROUP" ADD CONSTRAINT "FK_SECTIONGROUP_SECTIONGROUP_TEMPLATE" FOREIGN KEY("PARTIALVIEW") REFERENCES "ZKEACMS"."SECTIONTEMPLATE"("TEMPLATENAME") ;
ALTER TABLE "SECTIONGROUP" ADD CONSTRAINT "FK_SECTIONGROUP_SECTIONWIDGET" FOREIGN KEY("SECTIONWIDGETID") REFERENCES "ZKEACMS"."SECTIONWIDGET"("ID") ;
ALTER TABLE "SECTIONWIDGET" ADD CONSTRAINT "FK_SECTIONWIDGET_CMS_WIDGETBASE" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "STYLESHEETWIDGET" ADD CONSTRAINT "FK_STYLESHEETWIDGET_CMS_WIDGETBASE" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "USERROLERELATION" ADD CONSTRAINT "FK_USERROLERELATION_USERS" FOREIGN KEY("USERID") REFERENCES "ZKEACMS"."USERS"("USERID") ;
ALTER TABLE "USERROLERELATION" ADD CONSTRAINT "FK_USERROLERELATION_ROLES" FOREIGN KEY("ROLEID") REFERENCES "ZKEACMS"."ROLES"("ID") ;
ALTER TABLE "VIDEOWIDGET" ADD CONSTRAINT "FK_VIDEOWIDGET_CMS_WIDGETBASE" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "ARTICLE" ADD CONSTRAINT "FK_ARTICLE_ARTICLECATEGORY" FOREIGN KEY("ARTICLETYPEID") REFERENCES "ZKEACMS"."ARTICLETYPE"("ID") ;
ALTER TABLE "ARTICLEDETAILWIDGET" ADD CONSTRAINT "FK_ARTICLEDETAILWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "ARTICLELISTWIDGET" ADD CONSTRAINT "FK_ARTICLELISTWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "ARTICLESUMMARYWIDGET" ADD CONSTRAINT "FK_ARTICLESUMMARYWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "ARTICLETOPWIDGET" ADD CONSTRAINT "FK_ARTICLETOPWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "ARTICLETYPEWIDGET" ADD CONSTRAINT "FK_ARTICLETYPEWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "CAROUSELITEM" ADD CONSTRAINT "FK_CAROUSELITEM_CAROUSELWIDGET" FOREIGN KEY("CAROUSELWIDGETID") REFERENCES "ZKEACMS"."CAROUSELWIDGET"("ID") ;
ALTER TABLE "CAROUSELWIDGET" ADD CONSTRAINT "FK_CAROUSELWIDGET_CAROUSEL" FOREIGN KEY("CAROUSELID") REFERENCES "ZKEACMS"."CAROUSEL"("ID") ;
ALTER TABLE "CAROUSELWIDGET" ADD CONSTRAINT "FK_CAROUSELWIDGET_WIDGET" FOREIGN KEY("ID") REFERENCES "ZKEACMS"."CMS_WIDGETBASE"("ID") ;
ALTER TABLE "CMS_LAYOUTHTML" ADD CONSTRAINT "FK_CMS_LAYOUTHTML_CMS_LAYOUT" FOREIGN KEY("LAYOUTID") REFERENCES "ZKEACMS"."CMS_LAYOUT"("ID") ;
ALTER TABLE "CMS_PAGE" ADD CONSTRAINT "FK_CMS_PAGE_CMS_LAYOUT" FOREIGN KEY("LAYOUTID") REFERENCES "ZKEACMS"."CMS_LAYOUT"("ID") ;
ALTER TABLE "CMS_ZONE" ADD CONSTRAINT "FK_CMS_ZONE_CMS_LAYOUT" FOREIGN KEY("LAYOUTID") REFERENCES "ZKEACMS"."CMS_LAYOUT"("ID") ;
